name = "discord-cf-development"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "9e8f52a8c5264de5e77c5618d6dc32f9"
workers_dev = true

[env.staging]
name = "discord-cf-staging"

[env.production]
name = "discord-cf"
